= Projet APAS (Animation de programmes avec sémaphores)

Ce projet fournit une API pour créer simplement des animations
représentant des problèmes impliquant du multithreading.

=== Utilisation

Pour créer un programme utilisant cette API, il faut faire hériter votre classe principale de la classe apas.Animation (voir la doc de cette classe pour plus d'infos)

=== Installation
s
Pour créer un programme utilisant cette API, il faut d'abord faire un
maven install de ce projet, ensuite créez un nouveau projet
maven pour la nouvelle application avec un `pom.xml`
ayant la structure suivante :

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>myApplication</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>fr.orleans.univ.apas</groupId>
            <artifactId>apas</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.4</version>
                <configuration>
                    <mainClass>MainClass</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
----

N'oubliez pas de remplacer l' `artifactId` et le `groupId` au début du fichier
avec les infos de votre application, et de remplacer `MainClass` dans la partie
`<configuration>` du plugin `javafx-maven-plugin` par le nom de votre classe
principale (qui doit hériter de `apas.Application` pour rappel)